{{- include "ffc-helm-library.container-config-map" (list . "ffc-pay-statement-receiver.config-map") -}}
{{- define "ffc-pay-statement-receiver.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_CREATE_CONTAINERS: {{ quote .Values.container.azureStorageCreateContainers }}
  AZURE_STORAGE_CONTAINER: {{ quote .Values.container.storageContainer }}
  AZURE_STORAGE_FOLDER: {{ quote .Values.container.storageFolder }}
{{- end -}}
