environment: production
environmentCode:
name: ffc-pay-statement-receiver
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-statement-receiver

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-statement-receiver-config-map

containerSecret:
  name: ffc-pay-statement-receiver-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  redisHostname: hosty-mchost-face
  redisPort: 9999
  redisPassword: redis

ingress:
  class: nginx
  endpoint: ffc-pay-statement-receiver
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
