environment: production
environmentCode:
name: ffc-pay-statement-receiver
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-statement-receiver

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-statement-receiver-config-map

containerSecret:
  name: ffc-pay-statement-receiver-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  statementsEndpoint: http://ffc-pay-statement-receiver.ffc-pay
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID