services:
  ffc-pay-statement-receiver:
    build:
      context: .
      target: development
    image: ffc-pay-statement-receiver
    container_name: ffc-pay-statement-receiver
    depends_on:
      - ffc-pay-statement-receiver-redis
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-receiver-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      REDIS_HOSTNAME: ffc-pay-statement-receiver-redis
      REDIS_PASSWORD: redis

  ffc-pay-statement-receiver-redis:
    image: redis:6.2.7
