services:
  ffc-pay-statement-receiver:
    build:
      context: .
      target: production
    image: ffc-pay-statement-receiver
    container_name: ffc-pay-statement-receiver
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-receiver-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      REDIS_HOST: a
      REDIS_PASSWORD: a
