swagger: '2.0'
info:
  title: FFC Pay Statement Receiver
  version: '1.0.0'
host: ffc-pay-statement-receiver
schemes:
- http
paths:
  /statement/{version}/{filename}:
    example: /statement/v1/FFC_PaymentStatement_SFI_2022_1234567890_2022090615023001.pdf
    get:
      summary: Get statement file (in pdf format)
      produces:
      - application/pdf
      parameters:
        version: version of statement document to be downloaded
          example: v1
        filename: name of file to be downloaded
          example: FFC_PaymentStatement_SFI_2022_1234567890_2022090615023001.pdf
      responses:
        '200':
          description: readableStreamBody
          content:
        '400':
          description: no_filename
          reason: parameter filename not provided
        '404':
          description: file does not exist
          reason: file does not exist in blob storage
 